ProdavnicaWeb/Controllers/KorpaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProdavnicaWeb.Models;
using ProdavnicaWeb.Extensions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Http;
using ProdavnicaWeb.Services;


namespace ProdavnicaWeb.Controllers

{
    public class KorpaController : Controller
    {
        private readonly ProdavnicaWebContext db;
        private Korpa korpa;
        private KorpaServis kServis;

        public KorpaController(ProdavnicaWebContext _db, KorpaServis _kServis)
        {
            kServis = _kServis;
            db = _db;      
            korpa = kServis.CitajKorpu();
        }

       
        public IActionResult Index(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(korpa);
        }


        public IActionResult DodajStavku(int ProizvodId, string returnUrl)
        {
            Proizvod proizvod = db.Proizvodi
            .SingleOrDefault(p => p.ProizvodId == ProizvodId);

            if (proizvod != null)
            {
                korpa.DodajStavku(proizvod, 1);             
                kServis.CuvajKorpu(korpa);
               
            }
            return RedirectToAction("Index", new { returnUrl });
        }


        public IActionResult ObrisiStavku(int ProizvodId, string returnUrl)
        {
            Proizvod proizvod = db.Proizvodi
            .SingleOrDefault(p => p.ProizvodId == ProizvodId);

            if (proizvod != null)
            {
                korpa.ObrisiStavku(proizvod);
                kServis.CuvajKorpu(korpa);
            }
            return RedirectToAction("Index", new { returnUrl });
        }


        public IActionResult PromeniStavku(int ProizvodId, int kolicina, string returnUrl)
        {
            Proizvod proizvod = db.Proizvodi
            .SingleOrDefault(p => p.ProizvodId == ProizvodId);
            if (proizvod != null)
            {
                korpa.PromeniStavku(proizvod, kolicina);
                kServis.CuvajKorpu(korpa);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

    }
}

ProdavnicaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProdavnica</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/node_modules/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-fixed-top">
        <div class="container-fluid">
            <div class="container navbar-expand">
                <div class="navbar-nav">
                    <div class="navbar-brand">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="text-white">WebProdavnica</a>
                    </div>
                    <ul class="nav navbar mr-auto">
                        <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index">Pocetna</a></li>
                        <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="About">O nama</a></li>
                        <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Web Prodavnica</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.0.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ProdavnicaWeb/Views/Shared/_PrikaziProizvod.cshtml
@model Proizvod

<div class="card bg-dark text-white mt-1 pl-1">
    <h3>
        <strong>@Model.Naziv</strong>
        <span class="float-right badge-primary">
            @Model.Cena.ToString()
        </span>
    </h3>
    <form id="@Model.ProizvodId" asp-action="DodajStavku" asp-controller="Korpa"
          method="post">
        <input type="hidden" asp-for="ProizvodId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PutanjaQueryString()" />
        <span class="card-body p-0">
            @Model.Opis
            <button type="submit" class="btn btn-success btn-sm float-right">
                Dodaj u korpu
            </button>
        </span>
    </form>
</div>