ProdavnicaWeb/Models/Korpa.cs
using ProdavnicaWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProdavnicaWeb.Models
{
    public class Korpa
    {
        private List<StavkaKorpe> kolekcijaStavki = new List<StavkaKorpe>();

        public virtual void DodajStavku(Proizvod proizvod, int kolicina)
        {
            StavkaKorpe st = kolekcijaStavki
                .SingleOrDefault(p => p.Proizvod.ProizvodId == proizvod.ProizvodId);
               

            if (st == null)
            {
                st = new StavkaKorpe {
                    Proizvod = proizvod,
                    Kolicina = kolicina
                };
                kolekcijaStavki.Add(st);
            }
            else
            {
                st.Kolicina += kolicina;
            }
        }

        public virtual void ObrisiStavku(Proizvod proizvod)
        {
            StavkaKorpe st1 = kolekcijaStavki.SingleOrDefault(st => st.Proizvod.ProizvodId == proizvod.ProizvodId);
            kolekcijaStavki.Remove(st1);
        }
       

        public virtual void PromeniStavku(Proizvod proizvod, int kolicina)
        {
            StavkaKorpe st = kolekcijaStavki.SingleOrDefault(s => s.Proizvod.ProizvodId == proizvod.ProizvodId);

            if (st != null)
            {
                st.Kolicina = kolicina;
            }
        }
        public virtual decimal VrednostKorpe()
        {
           decimal vrednost= kolekcijaStavki.Sum(p => p.Proizvod.Cena * p.Kolicina);
            return vrednost;
        }
      

        public virtual void ObrisiKorpu()
        {
            kolekcijaStavki.Clear();
        }

        public IEnumerable<StavkaKorpe> Stavke
        {
            get
            {
                return kolekcijaStavki;
            }
        }
    }
}

ProdavnicaWeb/Controllers/KorpaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProdavnicaWeb.Models;
using ProdavnicaWeb.Extensions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Http;
using ProdavnicaWeb.Services;


namespace ProdavnicaWeb.Controllers

{
    public class KorpaController : Controller
    {
        private readonly ProdavnicaWebContext db;
        private Korpa korpa;
        private KorpaServis kServis;

        public KorpaController(ProdavnicaWebContext _db, KorpaServis _kServis)
        {
            kServis = _kServis;
            db = _db;      
            korpa = kServis.CitajKorpu();
        }

       
        public IActionResult Index(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(korpa);
        }


        public IActionResult DodajStavku(int ProizvodId, string returnUrl)
        {
            Proizvod proizvod = db.Proizvodi
            .SingleOrDefault(p => p.ProizvodId == ProizvodId);

            if (proizvod != null)
            {
                korpa.DodajStavku(proizvod, 1);             
                kServis.CuvajKorpu(korpa);
               
            }
            return RedirectToAction("Index", new { returnUrl });
        }


        public IActionResult ObrisiStavku(int ProizvodId, string returnUrl)
        {
            Proizvod proizvod = db.Proizvodi
            .SingleOrDefault(p => p.ProizvodId == ProizvodId);

            if (proizvod != null)
            {
                korpa.ObrisiStavku(proizvod);
                kServis.CuvajKorpu(korpa);
            }
            return RedirectToAction("Index", new { returnUrl });
        }


        public IActionResult PromeniStavku(int ProizvodId, int kolicina, string returnUrl)
        {
            Proizvod proizvod = db.Proizvodi
            .SingleOrDefault(p => p.ProizvodId == ProizvodId);
            if (proizvod != null)
            {
                korpa.PromeniStavku(proizvod, kolicina);
                kServis.CuvajKorpu(korpa);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

    }
}

ProdavnicaWeb/Controllers/KupovinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProdavnicaWeb.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using ProdavnicaWeb.Extensions;
using Microsoft.AspNetCore.Authorization;
using ProdavnicaWeb.Services;

namespace WebProdavnica.Controllers
{
    public class KupovinaController : Controller
    {
        private readonly ProdavnicaWebContext db;
        private readonly UserManager<ApplicationUser> um;
        
        private KorpaServis kServis;

        public KupovinaController(ProdavnicaWebContext _db, UserManager<ApplicationUser> _um, KorpaServis _kServis)
        {
            db = _db;
            um = _um;
            kServis = _kServis;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            Korpa korpa = kServis.CitajKorpu();
            if (korpa.Stavke.Count() == 0)
            {
                return RedirectToAction("Index", "Home");
            }
           
            ApplicationUser user = await um.GetUserAsync(User);
            string id = user.Id;
            Porudzbina p1 = new Porudzbina {
                KupacId = id,
                DatumKupovine = DateTime.Now
            };

            decimal ukupnaCena = 0;

            try
            {
                db.Porudzbine.Add(p1);
                db.SaveChanges();
                int pId = p1.PorudzbinaId;

                foreach (StavkaKorpe st in korpa.Stavke)
                {
                    Stavka st1 = new Stavka {
                        PorudzbinaId = pId,
                        ProizvodId = st.Proizvod.ProizvodId,
                        Kolicina = st.Kolicina
                    };

                    ukupnaCena = st.Proizvod.Cena * st.Kolicina + ukupnaCena;

                    db.Stavke.Add(st1);
                    db.SaveChanges();
                }
               
                kServis.ObrisiKorpu();

                ViewBag.UkupnaCena = ukupnaCena;

                return View(korpa);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
               
            }
           
        }
    }
}

ProdavnicaWeb/Views/Korpa/Index.cshtml
@model Korpa
<h2>Vasa korpa</h2>
<div class="row m-0">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Kolicina</th>
                <th>Stavka</th>
                <th class="text-right">Cena</th>
                <th class="text-right">Vrednost stavke</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (StavkaKorpe stavka in Model.Stavke)
            {
                <tr class="bg-dark text-white">
                    <td class="text-center">@stavka.Kolicina</td>
                    <td class="text-left">@stavka.Proizvod.Naziv</td>
                    <td class="text-right">@stavka.Proizvod.Cena.ToString()</td>
                    <td class="text-right">
                        @((stavka.Kolicina * stavka.Proizvod.Cena).ToString())
                    </td>
                    <td align="center">
                        <form asp-action="ObrisiStavku" method="post">
                            <input type="hidden" name="ProizvodId" value="@stavka.Proizvod.ProizvodId" />
                            <input type="hidden" name="returnUrl" value="@ViewBag.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger"> Ukloni</button>

                        </form>
                    </td>
                    <td>

                        <form asp-action="PromeniStavku" method="post">

                            <input type="hidden" name="ProizvodId" value="@stavka.Proizvod.ProizvodId" />
                            <input type="hidden" name="returnUrl" value="@ViewBag.ReturnUrl" />
                            <div class="input-group">
                                <input type="number" name="kolicina" value="@stavka.Kolicina" class="form-control" />
                                <span class="input-group-btn">
                                    <button class="btn btn-success ml-1" type="submit">Promeni</button>
                                </span>
                            </div>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Ukupno:</td>
                <td class="text-right">
                    @Model.VrednostKorpe().ToString()
                </td>
            </tr>
        </tfoot>
    </table>
</div>

<div class="btn-toolbar">
    <a class="btn btn-primary mr-auto" href="@ViewBag.ReturnUrl">Nastavi kupovinu</a>
    <form asp-action="Index" asp-controller="Kupovina">
        <button class="btn btn-success pr-5 pl-5">Kupi</button>
    </form>
</div>